<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> Forgot Passowrd </h2>
 
    <!-- Login Form -->
    <form method="POST" action="/UDPT-PROJECT/forgotpass/changepass">
    <p class="invalidFeedback" style="color:red">
        <?php if(isset($data)){echo $data["messenger"];}?>
      </p>
    <input type="password" id="password" class="fadeIn third" name="password" placeholder="Password">
      <input type="password" id="repassword" class="fadeIn third" name="repassword" placeholder="Repassword">
      <input type="submit" class="fadeIn fourth" value="Đổi mật khẩu">
    </form>
    
    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="/UDPT-PROJECT/login">Đăng nhập?</a>
    </div>

  </div>
</div>