<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> Forgot Passowrd </h2>
 
    <!-- Login Form -->
    <form>
      <input type="text" id="email" class="fadeIn second" name="email" placeholder="Email">
      <input type="submit" class="fadeIn fourth" value="Tiếp tục">
    </form>
    
    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="/UDPT-PROJECT/login">Đăng nhập?</a>
    </div>

  </div>
</div>