<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="inactive underlineHover"><a href="/UDPT-PROJECT/user/login"> Sign In </a></h2>
    <h2 class="active">Sign Up </h2>
  

    <!-- Login Form -->
    <form  method="post" >
      <input type="text" id="Username" class="fadeIn second" name="Username" placeholder="Username">
      <input type="text" id="password" class="fadeIn third" name="password" placeholder="Password">
      <input type="text" id="repassword" class="fadeIn third" name="repassword" placeholder="Repassword">
      <input type="text" id="name" class="fadeIn third" name="name" placeholder="Name">
      <input type="email" id="email" class="fadeIn third" name="email" placeholder="Email">
      <input type="date" id="birth" class="fadeIn third" name="birth" placeholder="Birth">
      <input type="text" id="phone" class="fadeIn third" name="phone" placeholder="Phone">
      <input type="submit" name = "signup" class="fadeIn fourth" value="Sign Up">
    </form>
     
    <!-- Remind Passowrd -->
    
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>

  </div>
</div>