<div class="col-sm-7" style="text-align: left; padding:1%">
    <div class="card" style="width: 100%;height: auto;overflow: hidden;padding: 1%;background-color: #fff;border-radius: 5px;box-shadow: 1% ">
        <div class="card-body" style="padding:1%">
            <div class="row">
                <div class="col-md-1">
                    <img src="<?php if ($question["user_image"] != null) {
                                    echo $question["user_image"];
                                } else {
                                    echo _PUBLIC . '/images/User.png';
                                }  ?>" height="40px" width="40px" style="background-color: transparent;margin-top: -5px; border-radius: 50%;">
                </div>
                <div class="col-md-9">
                    <b style="font-size: 20px;">
                        <?php echo $question["username"] ?> </b>
                    <p><?php echo $question["created"] ?> </p>
                    <b><?php echo $question["category_name"] ?> </b>

                </div>
            </div>
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <p style="background-color: #f6f6f6; padding:2%"><?php echo $question["description"] ?></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1"></div>
                <?php if (isset($question["tags"]) && count($question["tags"]) > 0) {
                    foreach ($question["tags"] as $tag) { ?>
                        <form method="POST" action="<?php echo _WEB_ROOT . "/Home/SearchByTag/tagname/1" ?>">
                            <input name="tagname" value="<?php echo $tag["DESCRIPTION"]; ?>" hidden />
                            <button name="submitSearchTagName" type="submit" class="col-md-1 btn" style="padding:1%; background-color: #028317; color: white;width: auto; margin-right:1%">
                                <?php echo $tag["DESCRIPTION"]; ?>
                            </button>
                        </form>
                <?php
                    }
                }
                ?>
            </div>
            <div class="row">
                <div class="col-md-9"></div>
                <div>
                    <p style="text-align: center;font-size: 15px;">
                        <span class="like" id="likes_of_<?php echo $question["id_question"] ?>"><?php echo $question["likes"] ?></span>
                        <button type="submit"  id="like_ques" style="border: none;background-color: #4CAF5000;"><span style="margin-left:1%;margin-right:1%; " class=" glyphicon glyphicon-thumbs-up" data-toggle="tooltip"></span></button>
                        <span id="answers_of_<?php echo $question["id_question"] ?>"><?php echo $question["anser"] ?></span>
                        <span class="glyphicon glyphicon-comment"></span>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <?php if (isset($_SESSION["jwt"])): ?>
    <div class="card" style="width: 100%;height: auto;overflow: hidden;padding: 1%;background-color: #fff;border-radius: 5px;box-shadow: 1%; margin-top:2% ">
        <div class="card-body" style="padding:1%">
            <div style="text-align: left;">
                <div style="text-align: center;">
                    <b style="font-size: 30px;">Trả lời câu hỏi</b>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlTextarea1" style="font-size: 20px;">Câu trả lời</label>
                    <textarea class="form-control" id="answer_des" name="answer_des" rows="5"></textarea>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="exampleFormControlSelect1" style="font-size: 20px;">Link tham khảo</label>
                        <input type="text" placeholder="Link tham khảo" name="link_tt" id="link_tt" />

                    </div>
                    <div class="form-group col-md-6">
                        <label for="exampleFormControlSelect1" style="font-size: 20px;">Link hình</label>
                        <input type="text" placeholder="Link hình" name="link_hinh" id="link_hinh" />

                    </div>
                </div>

                <div style="text-align: right;">
                    <button type="submit" class="btn btn-primary" id="createAns">Đăng câu trả lời</button>
                </div>
            </div>
        </div>
    </div>
    <?php endif;?>
    <div class="card" style="width:100%;height: auto;overflow: hidden;padding: 1%;background-color: #fff;border-radius: 5px;box-shadow:1%; margin-top:2% ">
        <div class="card-body" style="padding:1%">
            <div class="row">
                <b style="font-size: 35px; margin-left:2%">Trả lời</b>
            </div>
            <!-- // câu trả lời cho người dùng -->
            <?php if (isset($answer) && count($answer) > 0) {
                foreach ($answer as $ans) { ?>
                    <div>
                        <hr style="width:100%; size:10px; align:center " />
                        <div class="row">
                            <div class="col-md-1">
                                <img src="<?php if ($ans["user_image"] != null) {
                                                echo $ans["user_image"];
                                            } else {
                                                echo _PUBLIC . '/images/User.png';
                                            }  ?>" height="40px" width="40px" style="background-color: transparent;margin-top: -5px; border-radius: 50%;">
                            </div>
                            <div class="col-md-9">
                                <b style="font-size: 20px;"><?php echo $ans["username"] ?> </b>
                                <p><?php echo $ans["created"] ?> </p>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-md-1"></div>
                            <div class="col-md-11">
                                <p style="background-color: #f6f6f6; padding:2%"><?php echo $ans["content"] ?></p>

                                <?php
                                if ($ans["referencelink"] != null) {
                                    echo '<b style="font-size: 15px; margin-top:1%"> Nguồn tham khảo:<a href="' . $ans["referencelink"] . '" style="text-decoration: none;" target="_blank">Click here!!</a>';
                                }

                                ?>


                                </b>
                            </div>
                        </div>
                        
                        <?php if ($ans["referenceimage"] != null) : ?>
                            <div class="row" style=" margin-top:3%">
                                <div class="col-md-1"></div>
                                <div class="col-md-10">
                                    <b style="font-size: 15px; margin-top:3%"> Hình ảnh: </b>
                                    <a type="button" class="btn btn-info" href="<?php echo $ans["referenceimage"] ?>" style="width:100px; height:100px;margin:2%;background-image: url('<?php echo $ans["referenceimage"] ?>'); background-size: 100px 100px;   " target="_blank"></a>
                                    (click vào hình để mở bằng trang khác)
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="row">
                            <div class="col-md-9"></div>
                            <div>
                                <p style="text-align: right;font-size: 15px; margin-right:2%">
                                    <span style="color:#00000000"><?php echo $ans["id_answer"]?></span>
                                    <span id="likes_ans_of_<?php echo $ans["id_answer"] ?>"><?php echo $ans["likes"] ?></span>
                                    <button id="like_ans_<?php echo $ans["id_answer"] ?>" type="submit"  class="like_ans" style="border: none;background-color: #4CAF5000;"><span style="margin-left:1%;margin-right:1%; " class="glyphicon glyphicon-thumbs-up">
                                    </span></button>
                                </p>
                            </div>
                        </div>

                    </div>
            <?php
                }
            } ?>
        </div>
    </div>
</div>
<div class="col-sm-3" style="text-align: left; padding:1%">
    <?php if(isset($_SESSION["jwt"])){?>    
        <div class="card" style="width: 100%;height: auto;overflow: hidden;padding: 1%;background-color: #fff;border-radius: 5px;box-shadow: 1% ">
            <div class="card-body" style="padding:2%">
                <div class="row">
                    <div class="col-md-2">
                        <img src="<?php echo $data["user_profile"]["image"]?>" height="40px" width="40px" style="background-color: transparent;margin-top: 5px; border-radius: 10%;">
                    </div>
                    <div class="col-md-9" style="margin-left:3%">
                        <div class="row">
                            <b style="font-size: 16px;"><?php echo $data["user_profile"]['name']?></b>
                            <p style="font-size: 12px;"><?php echo $data["user_profile"]['email']?></p>
                        </div>
                    </div> 
                </div>
                <div class="row" style="margin-top:2%">
                    <p class="col-md-12" style="font-size: 15px;">Số câu hỏi: <b><?php echo $data["user_profile"]['ques']?></b></p>
                    <p class="col-md-12" style="font-size: 15px;">Số câu trả lời: <b><?php echo $data["user_profile"]['answer']?></b></p>
                    <p class="col-md-12" style="font-size: 15px;"></span><b>Thứ hạng (Tháng):    </b> <b style="font-size: 20px; color:#db9b00">   <?php echo $data["user_profile"]['top']?></b>  <span style="margin-left:1%;margin-right:1%; " class="glyphicon glyphicon-signal"></p>
                    <p class="col-md-12" style="color:#db9b00;text-align: center;">Hãy tích cực trả lời câu hỏi để tăng thứ hạng của mình bạn nhé!!</p>
                </div>
            </div>
        </div>
    <?php }?>
    <div class="card" style="width: 100%;height: auto;overflow: hidden;padding: 1%;background-color: #00000000;border-radius: 5px;box-shadow: 1%; margin-top: 2% ">
        <div class="card-body" style="padding:2%">
            <div style="text-align: center; font-size: 20px;color:#db9b00;">
                <a href="<?php echo _WEB_ROOT."/Home/Ranking"?>" style="color:#db9b00; margin-bottom:3%"><B>THÀNH VIÊN HĂNG HÁI NHẤT</B></a>
            </div>
            <?php if (isset($top) && count($top) > 0) {
                foreach ($top as $to) {?>
                    <div class="row" style="vertical-align: middle;">
                        <div class="col-md-2">
                            <img src=" <?php if($to["image"] != null){echo $to['image'];}else{ echo _PUBLIC."/images/User.png";} ?>" height="40px" width="40px" style="background-color: transparent;margin-top: 5px; border-radius: 10%;">
                        </div>
                        <div class="col-md-7" style="padding-top:5%;padding-bottom:2%; ">
                            <a href="<?php echo _WEB_ROOT."/userProfile/".$to["id_user"]?>" style="color:black;text-decoration: none;" ><p style="font-size: 14px;"><?php echo $to['name']?></p></a>
                        </div>
                        <div class="col-md-3" style="text-align: right; padding-top:5%;padding-bottom:2%;">
                            <b style="font-size: 12px;"><?php echo $to['answer']?> Câu</b>
                        </div>

                    </div>
            <?php } 
            } ?>
        </div>
    </div>
    <div class="card" style="width: 100%;height: auto;overflow: hidden;padding: 1%;background-color: #00000000;border-radius: 5px;box-shadow: 1%; margin-top: 2%">
        <div class="card-body" style="padding:2%">
            <div style="text-align: center; font-size: 20px;">
                <B>Bạn muốn hỏi điều gì?</B>
            </div>
            <?php if(!isset($_SESSION["jwt"])) {echo '<a href="'._WEB_ROOT.'/login" style="width:100%">';}?>
            <button style="width:100%;background-color: #db9b00;padding: 12px;text-align: center;color: #fff;border-radius: 5px;text-transform: uppercase;font-weight: 700;margin-top:3%"<?php if(isset($_SESSION["jwt"])){ echo 'data-toggle="modal" data-target="#makequestion"';} ?>  ><img src="https://hoidap247.com/static/img/icon-question.png" style="margin-right:2%">Đặt câu hỏi</button>
            <?php if(!isset($_SESSION["jwt"])) {echo "</a>";}?>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        <?php
        $url =  _API_ROOT . "/question/read-accepted-and-not-deleted.php";
        ?>
        setInterval(() => {
            fetch('<?php echo $url ?>')
                .then(
                    function(response) {
                        if (response.status !== 200) {
                            console.log('Lỗi, mã lỗi ' + response.status);
                            return;
                        }
                        // parse response data
                        response.json().then(data => {
                            var questions = data['res']['questions'];
                            for (var question of questions) {
                                $('#likes_of_' + question["id_question"]).text(question['likes']);
                                $('#answers_of_' + question["id_question"]).text(question['comment']);
                            }
                        })
                    }
                )
                .catch(err => {
                    console.log('Error :-S', err)
                });
        }, 100);
        
        setInterval(() => {
            var data = {ques_id: <?php echo $question["id_question"];?>};
            fetch("<?php echo _API_ROOT.'answer/getByidQues.php' ?>", {
            method: 'POST', 
            body: JSON.stringify(data), 
            headers:{
                'Content-Type': 'application/json'
            }
            })
            .then(
                    function(response) {
                        if (response.status !== 200) {
                            console.log('Lỗi, mã lỗi ' + response.status);
                            return;
                        }
                        // parse response data
                        response.json().then(data => {
                            var ans = data;
                            for (var answer of ans  ) {
                                $("#likes_ans_of_"+answer["id_answer"]).text(answer['likes']);
                                
                            }
                        })
                    }
                )
                .catch(err => {
                    console.log('Error :-S', err)
                });
        }, 100);

        $("#createAns").on("click", function(e) {
            $("#loadMe").modal({
                backdrop: "static", //remove ability to close modal with click
                keyboard: false, //remove option to close with keyboard
                show: true //Display loader!
            });
            var datas = {
                "id_question": <?php echo $question["id_question"] ?>,
                "content": $('#answer_des').val(),
                "referencelink": $('#link_tt').val(),
                "referenceimage": $('#link_hinh').val(),
                "id_user": "<?php echo $_SESSION["user_id"] ?>",
                "jwt": "<?php echo $_SESSION["jwt"] ?>"
            }
            $.ajax({
                contentType: 'application/json; charset=utf-8',
                type: "POST",
                url: "<?php echo (_API_ROOT . 'answer/create.php') ?>",
                dataType: "json",
                success: function(result, status, xhr) {
                    $("#loadMe").modal("hide");
                    alert("Gửi câu trả lời thành công. Đợi admin xét duyệt bạn nhé.");
                    $('#answer_des').val("");
                    $('#link_tt').val("");
                    $('#link_hinh').val("");
                },
                error: function(xhr, status, error) {
                    if (xhr.status == 401) {
                        $("#loadMe").modal("hide");
                        alert("Phiên đăng nhập của bạn đã hết. Xin vui lòng đăng nhập lại");
                        window.location = "<?php echo _WEB_ROOT . "/login/logout"; ?>";
                    } else {
                        $("#loadMe").modal("hide");
                        alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                    }

                },
                data: JSON.stringify(datas)
            });

        });

        $('[data-toggle="tooltip"]').tooltip();

        $("#like_ques").on("click", function() {
            var data = {
                "question_id": <?php echo $question["id_question"] ?>,
                "owner_id": "<?php echo $_SESSION["user_id"] ?>",
                "jwt": "<?php echo $_SESSION["jwt"] ?>"
            };

            $.ajax({
                contentType: 'application/json; charset=utf-8',
                type: "POST",
                url: "<?php echo (_API_ROOT . 'likes/create_ques.php') ?>",
                dataType: "json",
                success: function(result, status, xhr) {
                    
                    if(result.check == 1)
                    {
                        var result = document.getElementById("like_ques");
                        result.style.color = "#db9b00";
                        var result1 = document.getElementById("likes_of_<?php echo $question["id_question"] ?>");
                        result1.style.color = "#db9b00";
                    }
                    else
                    {
                        var result = document.getElementById("like_ques");
                        result.style.color = "black";
                        var result1 = document.getElementById("likes_of_<?php echo $question["id_question"] ?>");
                        result1.style.color = "black";
                    }
                },
                error: function(xhr, status, error) {
                    if (xhr.status == 401) {
                        $("#loadMe").modal("hide");
                        alert("Phiên đăng nhập của bạn đã hết. Xin vui lòng đăng nhập lại");
                        window.location = "<?php echo _WEB_ROOT . "/login/logout"; ?>";
                    } else {
                        $("#loadMe").modal("hide");
                        alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                    }

                },
                data: JSON.stringify(data)
            });

        });

        $(".like_ans").on("click", function() {
            const td = $(this).parent('div').find('span');
            var i = td[0].innerHTML;

            var data = {
                "answer_id": i,
                "owner_id": "<?php echo $_SESSION["user_id"] ?>",
                "jwt": "<?php echo $_SESSION["jwt"] ?>"
            };

            $.ajax({
                contentType: 'application/json; charset=utf-8',
                type: "POST",
                url: "<?php echo (_API_ROOT . 'likes/create_ans.php') ?>",
                dataType: "json",
                success: function(result, status, xhr) {
                    if(result.check == 1)
                    {
                        var result = document.getElementById("like_ans_"+i);
                        result.style.color = "#db9b00";
                        
                        var result1 = document.getElementById("likes_ans_of_"+i);
                        result1.style.color = "#db9b00";
                    }
                    else
                    {
                        var result = document.getElementById("like_ans_"+i);
                        result.style.color = "black";
                        var result1 = document.getElementById("likes_ans_of_"+i);
                        result1.style.color = "black";
                    }
                },
                error: function(xhr, status, error) {
                    if (xhr.status == 401) {
                        $("#loadMe").modal("hide");
                        alert("Phiên đăng nhập của bạn đã hết. Xin vui lòng đăng nhập lại");
                        window.location = "<?php echo _WEB_ROOT . "/login/logout"; ?>";
                    } else {
                        $("#loadMe").modal("hide");
                        alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                    }

                },
                data: JSON.stringify(data)
            });

        });


    });

</script>