<div class="col-sm-7" style="text-align: left; padding:1%">
    <div class="card" style="width: calc(100% - 48px);height: auto;overflow: hidden;padding: 1%;background-color: #fff;border-radius: 5px;box-shadow: 1% ">
        <div class="card-body" style="padding:1%">
            <div class="row">
                <div class="col-md-1">
                    <img src="<?php if ($question["user_image"] != null) {
                                    echo $question["user_image"];
                                } else {
                                    echo _PUBLIC . '/images/User.png';
                                }  ?>" height="40px" width="40px" style="background-color: transparent;margin-top: -5px; border-radius: 50%;">
                </div>
                <div class="col-md-9">
                    <b style="font-size: 20px;">
                        <?php echo $question["username"] ?> </b>
                    <p><?php echo $question["created"] ?> </p>
                    <b><?php echo $question["category_name"] ?> </b>

                </div>
            </div>
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <p><?php echo $question["description"] ?></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1"></div>
                <?php if (isset($question["tags"]) && count($question["tags"]) > 0) {
                    foreach ($question["tags"] as $tag) { ?>
                        <button onclick='window.location.href="<?php echo _WEB_ROOT . "/Home/Search/" . trim($tag["DESCRIPTION"]) . '/1' ?>"' type="submit" class="col-md-1 btn" style="padding:1%; background-color: #028317; color: white;width: auto; margin-right:1%">
                            <?php echo $tag["DESCRIPTION"]; ?>
                        </button>
                <?php
                    }
                }
                ?>
            </div>
            <div class="row">
                <div class="col-md-9"></div>
                <div>
                    <p style="text-align: center;font-size: 15px;">
                        <span id="likes_of_<?php echo $question["id_question"] ?>"><?php echo $question["likes"] ?></span>
                        <span style="margin-left:1%;margin-right:1%; " class="glyphicon glyphicon-thumbs-up">
                        </span>
                        <span id="answers_of_<?php echo $question["id_question"] ?>"><?php echo $question["anser"] ?></span>
                        <span class="glyphicon glyphicon-comment"></span>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="card" style="width: calc(100% - 48px);height: auto;overflow: hidden;padding: 1%;background-color: #fff;border-radius: 5px;box-shadow:1%; margin-top:2% ">
        <div class="card-body" style="padding:1%">
            <div class="row">
                <b style="font-size: 35px; margin-left:2%">Trả lời</b>
            </div>
            <!-- // câu trả lời cho người dùng -->
            <?php if (isset($answer) && count($answer) > 0) {
                foreach ($answer as $ans) { ?>
                    <div>
                        <hr style="width:30%; size:10px; align:center;" />
                        <div class="row">
                            <div class="col-md-1">
                                <img src="<?php if ($ans["user_image"] != null) {
                                                echo $ans["user_image"];
                                            } else {
                                                echo _PUBLIC . '/images/User.png';
                                            }  ?>" height="40px" width="40px" style="background-color: transparent;margin-top: -5px; border-radius: 50%;">
                            </div>
                            <div class="col-md-9">
                                <b style="font-size: 20px;"><?php echo $ans["username"] ?> </b>
                                <p><?php echo $ans["created"] ?> </p>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-1"></div>
                            <div class="col-md-10">
                                <p><?php echo $ans["content"] ?></p>

                                <?php
                                if ($ans["referencelink"] != null) {
                                    echo '<b style="font-size: 15px; margin-top:1%"> Nguồn tham khảo:<a href="' . $ans["referencelink"] . '" style="text-decoration: none;" target="_blank">Click here!!</a>';
                                }

                                ?>


                                </b>
                            </div>
                        </div>
                        <?php if ($ans["referenceimage"] != null) : ?>
                            <div class="row" style=" margin-top:3%">
                                <div class="col-md-1"></div>
                                <div class="col-md-10">
                                    <b style="font-size: 15px; margin-top:3%"> Hình ảnh: </b>
                                    <a type="button" class="btn btn-info" href="<?php echo $ans["referenceimage"] ?>" style="width:100px; height:100px;margin:2%;background-image: url('<?php echo $ans["referenceimage"] ?>'); background-size: 100px 100px;   " target="_blank"></a>
                                    (click vào hình để mở bằng trang khác)
                                </div>
                            </div>
                        <?php endif; ?>


                    </div>
            <?php
                }
            } ?>
        </div>
    </div>
</div>
<div class="col-sm-3">

</div>

<script type="text/javascript">
    $(document).ready(function() {
        <?php
        $url =  _API_ROOT . "/question/read-accepted-and-not-deleted.php";
        ?>
        setInterval(() => {
            fetch('<?php echo $url ?>')
                .then(
                    function(response) {
                        if (response.status !== 200) {
                            console.log('Lỗi, mã lỗi ' + response.status);
                            return;
                        }
                        // parse response data
                        response.json().then(data => {
                            var questions = data['res']['questions'];
                            for (var question of questions) {
                                $('#likes_of_' + question["id_question"]).text(question['likes']);
                                $('#answers_of_' + question["id_question"]).text(question['comment']);
                            }
                        })
                    }
                )
                .catch(err => {
                    console.log('Error :-S', err)
                });
        }, 3000);

    }, );
</script>