<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="inactive underlineHover"><a href="index.php?action=login"> Sign In </a></h2>
    <h2 class="active">Sign Up </h2>


    <!-- Login Form -->
    <form>
      <input type="text" id="login" class="fadeIn second" name="signup" placeholder="Username">
      <input type="text" id="password" class="fadeIn third" name="signup" placeholder="Password">
      <input type="text" id="repassword" class="fadeIn third" name="signup" placeholder="Repassword">
      <input type="text" id="name" class="fadeIn third" name="signup" placeholder="Name">
      <input type="email" id="email" class="fadeIn third" name="signup" placeholder="Email">
      <input type="date" id="birth" class="fadeIn third" name="signup" placeholder="Birth">
      <input type="submit" class="fadeIn fourth" value="Log In">
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>

  </div>
</div>