<footer class="mainfooter" role="contentinfo">
    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <!--Column1-->
                    <div class="footer-pad">
                        <a href="/UDPT-PROJECT">
                            <img src="/UDPT-PROJECT/public/images/Logo.jpg" height="80px" width="100px" style="border-radius: 5px;margin-left: 30px;" />
                            <h4><b>Question And Answer</b></h4>
                        </a>

                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <!--Column1-->
                    <div class="footer-pad">
                        <h4><b>Address</b></h4>
                        <ul class="list-unstyled">
                            <li><a href="#">225-227 Nguyen Van Cu Street, 5 District, HCMC</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <!--Column1-->
                    <div class="footer-pad">
                        <h4><b>Contact Info</b></h4>
                        <ul class="list-unstyled">
                            <li><a href="#">Phone: 0228 676767 34</a></li>
                            <li><a href="#">Mobile Phone: 0923290076</a></li>
                            <li><a href="#">Email: quilq@spc-technology.com</a></li>
                            <li><a href="#">Fax: 12311122221</a></li>
                            <li>
                                <a href="#"></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3">
                    <h4><b>Follow Us</b></h4>
                    <ul class="social-network social-circle">
                        <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 copy">
                    <p class="text-center">&copy; Copyright 2018 - Company Name. All rights reserved.</p>
                </div>
            </div>


        </div>
    </div>
</footer>