<!DOCTYPE html>
<html lang="en">

<head>
    <title>Question And Answer</title>
    <meta charset="utf-8">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/UDPT-PROJECT/public/css/profile.css"> 
</head>

<body style="background: -webkit-linear-gradient(left, #3931af, #00c6ff)">
<?php require($VIEW); ?>
</body>
</html>