<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> Sign In </h2>
    <h2 class="inactive underlineHover"><a href="/UDPT-PROJECT/signup">Sign Up </a></h2>

   

    <!-- Login Form -->
    <form method ="POST" action="/UDPT-PROJECT/login/loginpost" >
      
      <input type="text" id="login" class="fadeIn second" name="username" placeholder="Username">
      <input type="password" id="password" class="fadeIn third" name="password" placeholder="Password">
      <input type="submit" class="fadeIn fourth" value="Log In">
      <p class="invalidFeedback" style="color:red">
        <?php if(isset($data)){echo $data["messenger"];}?>
      </p>
    </form>
    
    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="/UDPT-PROJECT/forgotpass">Forgot Password?</a>
    </div>

  </div>
</div>