<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> OTP</h2>
 
    <!-- Login Form -->
    <form method="POST" action="/UDPT-PROJECT/signup/otppost"> 
    <p class="invalidFeedback" style="color:red">
        <?php if(isset($data)){echo $data["messenger"];}?>
      </p>
      <input type="text" class="fadeIn second" name="otpvalue" placeholder="OTP">
      <input type="submit" class="fadeIn fourth" value="Tiếp tục" name="save">
      <?php echo "<p id=\"email\" style=\"color:white\">".$_SESSION['user']["email"]."</p> "
    ?>
    </form>
    <p class="w3-center"><button class="w3-btn w3-green w3-round" style="width:40%;height:40px" id="sendOtp">Resend OTP</button></p>
    
    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="/UDPT-PROJECT/login">Đăng nhập?</a>
    </div>

  </div>
</div>
<?php require_once "./app/config.php";?>
<script type="text/javascript">
$(document).ready(function(){
  $("#sendOtp").on("click", function(e){ 
    e.preventDefault();    
    var email = $("#email").text();
    $.ajax({
      headers: {
      'Connection': 'Keep-Alive',
      'Content-Type': 'application/json; charset=utf-8'
      },
      type : "POST",
      url  : _API_ROOT.'SendOTP/sendotp.php',
      dataType: "json",
      data : {email:email},
      success:function(result, status, xhr){
        alert(xhr.status);
        alert("hahaah");
      },
      error: function (xhr, status, error) {
        alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
      }
    });  
      
    });   
});
</script>