<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> OTP</h2>
 
    <!-- Login Form -->
    <form method="POST" action="<?php echo _WEB_ROOT ?>/signup/otppost"> 
    <p class="invalidFeedback" style="color:red">
        <?php if(isset($data)){echo $data["messenger"];}?>
      </p>
      <input type="text" class="fadeIn second" name="otpvalue" placeholder="OTP">
      <input type="submit" class="fadeIn fourth" value="Tiếp tục" name="save">
      <?php echo "<p id=\"email\" style=\"color:white\">".$_SESSION['user']["email"]."</p> "
    ?>
    <p><?php echo $_SESSION['otp']?></p>
    </form>
    <p class="w3-center"><button class="w3-btn w3-green w3-round" style="width:40%;height:40px" id="sendOtp">Resend OTP</button></p>
    
    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="<?php echo _WEB_ROOT ?>/login">Đăng nhập?</a>
    </div>

  </div>
</div>
<?php require_once "./app/config.php";?>
<script type="text/javascript">
$(document).ready(function(){
  $("#sendOtp").on("click", function(e){ 
    e.preventDefault(); 
    $("#loadMe").modal({
      backdrop: "static", //remove ability to close modal with click
      keyboard: false, //remove option to close with keyboard
      show: true //Display loader!
    });     
    var email = 
    {
      email: "<?php echo $_SESSION['email']?>",
      otp: "<?php  $rndno=rand(100000, 999999);
        echo $rndno;
      ?>"
    }
    $.ajax({
      headers: {
      'Connection': 'Keep-Alive',
      'Content-Type': 'application/json; charset=utf-8'
      },
      url  : "<?php echo _API_ROOT.'SendOTP/sendotp.php' ?>",
      type : "POST",
      data : JSON.stringify(email),
      success:function(result){
        $("#loadMe").modal("hide");
        alert("Đã gửi otp");
      },
      error: function (xhr, thrownError, result) {
        alert(xhr.status);
        alert(thrownError);
      }
    });  
      
    });   
});
</script>