<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="inactive underlineHover"><a href="/UDPT-PROJECT/login"> Sign In </a></h2>
    <h2 class="active">Sign Up </h2>
  

    <!-- Login Form -->
    <form  method="post" action="/UDPT-PROJECT/signup/signuppost">
      <input type="text" id="username" class="fadeIn second" name="username" placeholder="Username">
      <input type="password" id="password" class="fadeIn third" name="password" placeholder="Password">
      <input type="password" id="repassword" class="fadeIn third" name="repassword" placeholder="Repassword">
      <input type="text" id="name" class="fadeIn third" name="name" placeholder="Name">
      <input type="email" id="email" class="fadeIn third" name="email" placeholder="Email">
      <input type="date" id="birth" class="fadeIn third" name="birth" placeholder="Birth">
      <input type="text" id="phone" class="fadeIn third" name="phone" placeholder="Phone">
      <input type="submit" name = "signup" class="fadeIn fourth disabled" value="Sign Up">
      <p class="invalidFeedback" style="color:red">
        <?php if(isset($data)){echo $data["messenger"];}?>
      </p>
    </form>
     
    <!-- Remind Passowrd -->
    
    <div id="formFooter">
      <a class="underlineHover" href="/UDPT-PROJECT/forgotpass">Forgot Password?</a>
    </div>

  </div>
</div>
<scrip>
