<div class="col-sm-2 sidenav">

    <p style="background-color:moccasin;"><a href="#"><b>Topic</b></a></p>
    <p><a href="#"><b>Technology</b></a></p>
    <p><a href="#"><b>Society</b></a></p>
      
</div>
<div class="col-sm-7" style="text-align: left; padding-top:1%">
    <div class="card" style="width: width: 100%;height: auto;overflow: hidden;padding: 1%;background-color: #fff;border-radius: 5px;box-shadow: 1% ;">
        <div class="card-body" style="padding:1%">
            
        </div>
    </div>
    <div class="card" style="width: width: 100%;height: auto;overflow: hidden;padding: 1%;background-color: #fff;border-radius: 5px;box-shadow: 1% ; margin-top:1%">
        <div class="card-body" style="padding:1%">
            
        </div>
    </div>
</div>
<div class="col-sm-3" style="text-align: left; padding-top:1%">
    <div class="card" style="width: width: 100%;height: auto;overflow: hidden;padding: 1%;background-color: #fff;border-radius: 5px;box-shadow: 1% ">
        <div class="card-body" style="padding:1%">
            
        </div>
    </div>

</div>

